easy_admin:
   entities:
#        # List the entity class name you want to manage
    BienModification:
        class: App\Entity\BienModification
        list:
            fields: ['localisation']
#        - App\Entity\Category
#        - App\Entity\User
